import type { MisoSource } from "./types";

/**
 * Validated MISO source registry. The AI orchestration layer may ONLY select a
 * source from this registry — it never invents endpoints.
 */
export const MISO_SOURCES: MisoSource[] = [
  {
    source_id: "miso_actual_load",
    name: "Actual Load",
    type: "api",
    description: "Actual electrical load (demand) across MISO regions.",
    supports: ["actual load", "power usage", "demand", "historical load"],
    requires_authentication: true,
    supports_api_generation: true,
    supports_visualization: true,
    endpoint: "https://apim.misoenergy.org/pricing/v1/actual-load",
    method: "GET",
    value_label: "Load",
    unit: "MW",
    documentation_url: "https://apim.misoenergy.org/",
    parameters: [
      {
        name: "start_date",
        label: "Start date",
        type: "date",
        required: true,
        description: "First day of the requested range (YYYY-MM-DD).",
        example: "2026-09-05",
      },
      {
        name: "end_date",
        label: "End date",
        type: "date",
        required: true,
        description: "Last day of the requested range (YYYY-MM-DD).",
        example: "2026-09-05",
      },
      {
        name: "region",
        label: "Region",
        type: "enum",
        required: false,
        description: "MISO local resource zone or state.",
        options: ["MISO", "North", "Central", "South", "Indiana", "Michigan", "Louisiana"],
      },
    ],
  },
  {
    source_id: "miso_forecasted_load",
    name: "Forecasted Load",
    type: "api",
    description: "Day-ahead and mid-term forecast of MISO system demand.",
    supports: ["forecast load", "load forecast", "expected demand", "tomorrow load"],
    requires_authentication: true,
    supports_api_generation: true,
    supports_visualization: true,
    endpoint: "https://apim.misoenergy.org/pricing/v1/forecasted-load",
    method: "GET",
    value_label: "Forecast load",
    unit: "MW",
    parameters: [
      { name: "start_date", label: "Start date", type: "date", required: true, description: "First day of the forecast window.", example: "2026-09-06" },
      { name: "end_date", label: "End date", type: "date", required: true, description: "Last day of the forecast window.", example: "2026-09-07" },
      { name: "region", label: "Region", type: "enum", required: false, description: "MISO region.", options: ["MISO", "North", "Central", "South"] },
    ],
  },
  {
    source_id: "miso_realtime_lmp",
    name: "Real-Time LMP",
    type: "api",
    description: "Real-time locational marginal prices at MISO pricing nodes and hubs.",
    supports: ["market prices", "lmp", "real time price", "energy price", "today prices"],
    requires_authentication: true,
    supports_api_generation: true,
    supports_visualization: true,
    endpoint: "https://apim.misoenergy.org/pricing/v1/real-time-lmp",
    method: "GET",
    value_label: "LMP",
    unit: "$/MWh",
    parameters: [
      { name: "start_date", label: "Start date", type: "date", required: true, description: "First trading day.", example: "2026-09-06" },
      { name: "end_date", label: "End date", type: "date", required: true, description: "Last trading day.", example: "2026-09-06" },
      { name: "node", label: "Node or hub", type: "string", required: false, description: "Pricing node, hub or zone name.", example: "INDIANA.HUB" },
    ],
  },
  {
    source_id: "miso_dayahead_lmp",
    name: "Day-Ahead LMP",
    type: "api",
    description: "Day-ahead cleared locational marginal prices.",
    supports: ["day ahead prices", "cleared prices", "dayahead lmp"],
    requires_authentication: true,
    supports_api_generation: true,
    supports_visualization: true,
    endpoint: "https://apim.misoenergy.org/pricing/v1/day-ahead-lmp",
    method: "GET",
    value_label: "Day-ahead LMP",
    unit: "$/MWh",
    parameters: [
      { name: "start_date", label: "Start date", type: "date", required: true, description: "First trading day.", example: "2026-09-06" },
      { name: "end_date", label: "End date", type: "date", required: true, description: "Last trading day.", example: "2026-09-06" },
      { name: "node", label: "Node or hub", type: "string", required: false, description: "Pricing node, hub or zone name.", example: "MICHIGAN.HUB" },
    ],
  },
  {
    source_id: "miso_generation_fuel_mix",
    name: "Generation Fuel Mix",
    type: "api",
    description: "Generation output by fuel type across the MISO footprint.",
    supports: ["generation", "fuel mix", "wind output", "solar output", "power results", "resource mix"],
    requires_authentication: true,
    supports_api_generation: true,
    supports_visualization: true,
    endpoint: "https://apim.misoenergy.org/generation/v1/fuel-mix",
    method: "GET",
    value_label: "Generation",
    unit: "MW",
    parameters: [
      { name: "start_date", label: "Start date", type: "date", required: true, description: "First day of the range.", example: "2026-09-05" },
      { name: "end_date", label: "End date", type: "date", required: true, description: "Last day of the range.", example: "2026-09-05" },
      { name: "region", label: "Region", type: "enum", required: false, description: "MISO region or state.", options: ["MISO", "North", "Central", "South", "Indiana", "Michigan", "Louisiana"] },
    ],
  },
  {
    source_id: "miso_interchange",
    name: "Net Scheduled Interchange",
    type: "api",
    description: "Net scheduled interchange between MISO and neighbouring balancing authorities.",
    supports: ["interchange", "imports", "exports", "transfers"],
    requires_authentication: true,
    supports_api_generation: true,
    supports_visualization: true,
    endpoint: "https://apim.misoenergy.org/operations/v1/net-scheduled-interchange",
    method: "GET",
    value_label: "Interchange",
    unit: "MW",
    parameters: [
      { name: "start_date", label: "Start date", type: "date", required: true, description: "First day of the range.", example: "2026-09-05" },
      { name: "end_date", label: "End date", type: "date", required: true, description: "Last day of the range.", example: "2026-09-05" },
    ],
  },
  {
    source_id: "miso_market_report_daily",
    name: "Daily Market Report",
    type: "report",
    description: "MISO daily market summary report covering prices, congestion and load.",
    supports: ["market report", "daily report", "latest report", "market summary"],
    requires_authentication: false,
    supports_api_generation: false,
    supports_visualization: false,
    documentation_url: "https://www.misoenergy.org/markets-and-operations/real-time--market-data/market-reports/",
    parameters: [
      { name: "report_date", label: "Report date", type: "date", required: false, description: "Publication date of the report.", example: "2026-09-05" },
    ],
  },
  {
    source_id: "miso_market_report_monthly",
    name: "Monthly Market Assessment",
    type: "report",
    description: "Independent Market Monitor monthly assessment of MISO market performance.",
    supports: ["monthly report", "market assessment", "imm report"],
    requires_authentication: false,
    supports_api_generation: false,
    supports_visualization: false,
    documentation_url: "https://www.misoenergy.org/markets-and-operations/real-time--market-data/market-reports/",
    parameters: [],
  },
  {
    source_id: "miso_historical_datasets",
    name: "Historical Market Datasets",
    type: "dataset",
    description: "Downloadable historical MISO market and operations datasets (CSV/ZIP archives).",
    supports: ["historical data", "download dataset", "archive", "bulk data"],
    requires_authentication: false,
    supports_api_generation: false,
    supports_visualization: false,
    documentation_url: "https://www.misoenergy.org/markets-and-operations/market-reports/",
    parameters: [
      { name: "year", label: "Year", type: "string", required: false, description: "Dataset year.", example: "2026" },
    ],
  },
  {
    source_id: "miso_api_documentation",
    name: "MISO API Documentation",
    type: "webpage",
    description: "MISO API portal describing available endpoints, products and subscription access.",
    supports: ["api documentation", "how to authenticate", "subscription key", "developer portal"],
    requires_authentication: false,
    supports_api_generation: false,
    supports_visualization: false,
    documentation_url: "https://apim.misoenergy.org/",
    parameters: [],
  },
];

export function getSource(sourceId: string): MisoSource | undefined {
  return MISO_SOURCES.find((s) => s.source_id === sourceId);
}

export const SOURCE_CATALOG_FOR_PROMPT = MISO_SOURCES.map((s) => ({
  source_id: s.source_id,
  name: s.name,
  type: s.type,
  description: s.description,
  supports: s.supports,
  parameters: (s.parameters ?? []).map((p) => ({
    name: p.name,
    required: p.required,
    type: p.type,
    options: p.options,
  })),
}));
